import React, { Fragment } from 'react';
import { Link } from 'react-router-dom';
import TopMenus from '../../components/aikit/TopMenus';
import MainContent from '../../components/aikit/MainContent';
import { SVGICON } from '../../constant/theme';
import { schedulerTable } from '../../constant/alldata';

const numb = [5, 9, 14];

function Scheduled() {
    return (
        <Fragment>
            <div className="row">
                <div className="col-xl-12">
                    <MainContent detail="This is a demo of AIKit plugin made for you to test the experience of using the plugin. "
                        subtitle="AIKit Scheduled AI Generators allow you to schedule content to be generated by AI. Please review and edit before publishing for best results. This is not a substitute for human editing, but a drafting aid. Happy writing!"
                    />
                    <TopMenus id={2} />
                    <div className="card h-auto">
                        <div className="card-body p-0">
                            <div id="employee-tbl_wrapper" className="table-responsive dataTables_wrapper active-projects style-1">
                                <table id="empoloyees-tblwrapper" className="table dataTable dataTables_wrapper no-footer mb-0">
                                    <thead>
                                        <tr>
                                            <th>Description</th>
                                            <th>Keywords</th>
                                            <th>Status</th>
                                            <th>Interval</th>
                                            <th>Last generation</th>
                                            <th>Next generation</th>
                                            <th>Is running</th>
                                            <th>Run count</th>
                                            <th>Max run count</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {schedulerTable.map((item, ind) => (
                                            <tr key={ind}>
                                                <td className="text-black">Write a rat story</td>
                                                <td> {item.keyword} </td>
                                                <td><span className="badge badge-success badge-sm light">Active</span></td>
                                                <td>hourly</td>
                                                <td>4:50 am July 11, 2025</td>
                                                <td>5:50 am July 11, 2025</td>
                                                <td>
                                                    {numb.includes(ind) ?
                                                        <span className="badge badge-success">Yes</span>
                                                        :
                                                        <span className="badge badge-light">No</span>
                                                    }
                                                </td>
                                                <td>1</td>
                                                <td>5</td>
                                                <td className="text-nowrap">
                                                    <Link to={"#"} className="btn btn-primary light btn-sharp"> {SVGICON.blueedit} </Link>{" "}
                                                    <Link to={"#"} className="btn btn-danger light btn-sharp"> {SVGICON.reddelete} </Link>
                                                </td>
                                            </tr>
                                        ))}
                                    </tbody>
                                </table>
                                <div className="d-sm-flex text-center justify-content-between align-items-center mb-3">
                                    <div className="mb-sm-0 mb-3 dataTables_info pt-0">
                                        <p className="mb-0 text-black">Showing 1 to 9 of 11 entries</p>
                                    </div>
                                    <nav className="dataTables_paginate paging_simple_numbers mb-0">
                                        <ul className="pagination pagination-circle">
                                            <li className="page-item page-indicator"> <Link className="page-link" to={"#"}> <i className="la la-angle-left" /></Link> </li>
                                            <li className="page-item active"><Link className="page-link" to={"#"}>1</Link> </li>
                                            <li className="page-item"><Link className="page-link" to={"#"}>2</Link></li>
                                            <li className="page-item page-indicator"> <Link className="page-link" to={"#"}> <i className="la la-angle-right" /></Link> </li>
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </Fragment>
    );
};

export default Scheduled;