import { createContext, useContext, useEffect, useState, useCallback } from 'react';

const LanguageContext = createContext(null);

const tr = {
  'nav.home': 'Ana Sayfa', 'nav.about': 'Hakkımızda', 'nav.services': 'Hizmetler',
  'nav.projects': 'Projeler', 'nav.gallery': 'Galeri', 'nav.faq': 'SSS',
  'nav.career': 'Kariyer', 'nav.contact': 'İletişim',
  'lang.tr': 'Türkçe', 'lang.en': 'English', 'lang.ar': 'العربية', 'lang.ru': 'Русский',

  'hero.badge': 'Küresel İş Ortağınız · 25+ Ülke',
  'hero.h1_pre': 'Dünyayı', 'hero.h1_grad': 'İş Ortağınızla', 'hero.h1_post': 'Keşfedin',
  'hero.sub': 'Uluslararası iş forumları ve ticaret heyetleri aracılığıyla firmaların dünya pazarlarına açılmasına stratejik destek sunuyoruz.',
  'hero.cta1': 'Teklif Alın', 'hero.cta2': 'Kazan Forum 2026',
  'hero.stat_country': 'Ülke', 'hero.stat_client': 'Müşteri', 'hero.stat_forum': 'Forum', 'hero.stat_year': 'Yıl',
  'hero.partners': 'Resmi Paydaşlar',

  'about.badge': 'Hakkımızda',
  'about.h2_pre': 'Küresel İş Dünyasında', 'about.h2_grad': 'Güvenilir Yol Arkadaşınız',
  'about.p1': 'Uluslararası organizasyonların karmaşık yapısını sadeleştirerek firmalara küresel pazarlarda güvenle ilerleme imkânı sunuyoruz.',
  'about.p2': 'Katar\'dan Japonya\'ya, Rusya\'dan Afrika\'ya kadar iş forumlarını ve ticaret heyetlerini uçtan uca planlıyoruz.',
  'about.point1': 'Bakanlık Düzeyinde Koordinasyon', 'about.point2': 'Uluslararası Organizasyon Deneyimi',
  'about.point3': 'Küresel Pazar Erişimi', 'about.point4': 'Sektörel Forum Uzmanlığı',
  'about.globe_hint': 'Küreye tıklayıp sürükleyin',
  'about.stat_country': 'Ülke', 'about.stat_year': 'Yıl', 'about.stat_forum': 'Forum',

  'services.badge': 'Hizmetlerimiz',
  'services.h2_pre': 'Küresel', 'services.h2_grad': 'Erişim Ağımız',
  'services.sub': 'Düğümlere tıklayın — her hizmetin içeriği ve bağlantılı alanları görüntülensin',

  'orbital.item1.title': 'Uluslararası İş Forumları', 'orbital.item1.category': 'Hizmet', 'orbital.item1.date': '2019',
  'orbital.item1.content': 'Katar, Japonya, Rusya ve Afrika gibi ülkelerde sektörel iş forumları ve ticaret heyetleri.',
  'orbital.item2.title': 'Bakanlık Koordinasyonu', 'orbital.item2.category': 'Strateji', 'orbital.item2.date': '2020',
  'orbital.item2.content': 'Birden fazla ülkenin ticaret bakanlığıyla resmi kanallar üzerinden doğrudan iş birliği.',
  'orbital.item3.title': 'Pazar Giriş Danışmanlığı', 'orbital.item3.category': 'Danışmanlık', 'orbital.item3.date': '2021',
  'orbital.item3.content': 'Yeni pazarlara açılmak isteyen firmalara strateji geliştirmeden ortaklığa uçtan uca danışmanlık.',
  'orbital.item4.title': 'Kazan Forum 2026', 'orbital.item4.category': 'Proje', 'orbital.item4.date': 'May 2026',
  'orbital.item4.content': '17. Uluslararası Ekonomi Forumu — Rusya / İslam Dünyası. Kazan, Tataristan.',
  'orbital.item5.title': 'Fuar & Expo', 'orbital.item5.category': 'Hizmet', 'orbital.item5.date': '2022',
  'orbital.item5.content': 'Tayland Expo, Rusya ProExpo, Berlin ITB gibi global fuarlarda Türk firmalarına katılım organizasyonu.',
  'orbital.item6.title': 'Helal Ekonomi', 'orbital.item6.category': 'Hizmet', 'orbital.item6.date': '2023',
  'orbital.item6.content': 'Mekke Helal Forumu ve Londra Helal Forumu platformlarında uzmanlaşmış çözümler.',
  'orbital.status.completed': 'Tamamlandı', 'orbital.status.inprogress': 'Devam Ediyor', 'orbital.status.pending': 'Beklemede',
  'orbital.capacity': 'Kapasite', 'orbital.related': 'Bağlantılı Alanlar',
  'orbital.pause': 'Durdur', 'orbital.rotate': 'Döndür',

  'whyus.badge': 'Neden SS Congress',
  'whyus.h2_pre': 'Güvenli ve', 'whyus.h2_grad': 'Etkili Ticaret', 'whyus.h2_post': 'Danışmanlığı',
  'whyus.feat1.title': 'Kanıtlanmış Küresel Deneyim',
  'whyus.feat1.desc': '4 kıta ve 25+ ülkede başarıyla tamamlanan organizasyonlarla uluslararası arenada referans noktasıyız.',
  'whyus.feat2.title': 'Bakanlık Düzeyinde Koordinasyon',
  'whyus.feat2.desc': 'Birden fazla ülkenin ticaret bakanlığıyla resmi kanallar üzerinden doğrudan iş birliği yapıyoruz.',
  'whyus.feat3.title': 'Hızlı ve Etkili Çözümler',
  'whyus.feat3.desc': 'Süreçleri hızlandıran stratejik yaklaşımımızla ticaretinizi bir üst seviyeye taşıyoruz.',
  'whyus.feat4.title': 'Hedef Odaklı Strateji',
  'whyus.feat4.desc': 'Büyüme hedeflerinize uygun, veriye dayalı ve sonuç odaklı danışmanlık sunuyoruz.',
  'whyus.stat_client': 'Müşteri', 'whyus.stat_country': 'Ülke', 'whyus.stat_forum': 'Forum', 'whyus.stat_year': 'Yıl',

  'projects.badge': 'Portföy', 'projects.h2': 'Projelerimiz',
  'projects.completed': 'Tamamlanan Projeler', 'projects.upcoming': 'Gelecek Projeler',
  'projects.past1': 'Katar İş Forumu 2024', 'projects.past1_loc': 'Doha, Katar',
  'projects.past2': 'Rusya ProExpo Katılımı', 'projects.past2_loc': 'Moskova, Rusya',
  'projects.past3': 'Londra Helal Forumu', 'projects.past3_loc': 'Londra, BK',
  'projects.past4': 'Mekke Helal Ekonomi Zirvesi', 'projects.past4_loc': 'Mekke, S. Arabistan',
  'projects.up1': 'Kazan Forum 2026', 'projects.up1_loc': 'Kazan, Tataristan', 'projects.up1_date': '12–17 Mayıs 2026',
  'projects.up2': 'Tayland Expo 2025', 'projects.up2_loc': 'Bangkok, Tayland', 'projects.up2_date': '2025',
  'projects.up3': 'Berlin ITB Türk Delegasyonu', 'projects.up3_loc': 'Berlin, Almanya', 'projects.up3_date': '2025',

  'gallery.badge': 'Galeri', 'gallery.h2': 'Sahne Arkasından',

  'footer.tagline': 'Dünya pazarlarına açılan firmalara stratejik, diplomatik ve organizasyonel destek sunan küresel ortağınız.',
  'footer.menu': 'Menü', 'footer.corporate': 'Kurumsal', 'footer.contact_title': 'İletişim',
  'footer.faq': 'SSS', 'footer.career': 'Kariyer',
  'footer.privacy': 'Gizlilik Politikası', 'footer.kvkk': 'KVKK Aydınlatma',
  'footer.copyright': '© SS CONGRESS 2025 — Tüm Hakları Saklıdır',

  'contact.badge': 'Bize Ulaşın', 'contact.h1': 'İletişim',
  'contact.sub': 'Sorularınız ve danışmanlık talepleriniz için bize ulaşın.',
  'contact.email_title': 'E-posta', 'contact.phone_title': 'Telefon',
  'contact.address_title': 'Adres', 'contact.hours_title': 'Çalışma Saatleri',
  'contact.hours_weekdays': 'Pazartesi - Cuma: 09:00 - 18:00',
  'contact.hours_saturday': 'Cumartesi: 10:00 - 14:00',
  'contact.form_title': 'Ücretsiz Danışmanlık Alın',
  'contact.field_name': 'Ad Soyad', 'contact.field_name_ph': 'Adınız Soyadınız',
  'contact.field_email': 'E-posta', 'contact.field_email_ph': 'email@sirket.com',
  'contact.field_company': 'Şirket Adı', 'contact.field_company_ph': 'Şirketinizin adı',
  'contact.field_message': 'Mesajınız', 'contact.field_message_ph': 'Hangi konuda destek almak istersiniz?',
  'contact.submit': 'Randevu Talebi Gönder',

  'about_page.badge': 'Hakkımızda',
  'about_page.h1_pre': 'Küresel İş Dünyasında', 'about_page.h1_grad': 'Güvenilir Yol Arkadaşınız',
  'about_page.p1': 'Uluslararası organizasyonların karmaşık yapısını sadeleştirerek firmalara küresel pazarlarda güvenle ilerleme imkânı sunuyoruz.',
  'about_page.p2': 'Katar\'dan Japonya\'ya, Rusya\'dan Afrika\'ya kadar iş forumlarını ve ticaret heyetlerini uçtan uca planlıyor ve yönetiyoruz.',
  'about_page.vision_badge': 'Vizyonumuz',
  'about_page.vision_quote': '"Dış ticarette güven, her adımda sürdürülebilirlik."',
  'about_page.process_badge': 'İş Sürecimiz', 'about_page.process_h2': 'Yaklaşımımız',
  'about_page.wf1.title': 'Büyüme Girişimleri',
  'about_page.wf1.desc': 'İşletmelerin büyüme yolculuğunu stratejik çözümlerle destekliyor, sürdürülebilir başarıya ulaştırıyoruz.',
  'about_page.wf2.title': 'Danışmanlık Hizmetleri',
  'about_page.wf2.desc': 'Uzman ekibimizle iş kararlarınıza rehberlik ediyor, geleceğe uygun stratejiler geliştiriyoruz.',
  'about_page.wf3.title': 'Küresel Girişimler',
  'about_page.wf3.desc': 'Veri odaklı analiz ve yenilikçi yöntemlerle işinizi hızlandırıyor, küresel pazarlara açıyoruz.',
  'about_page.stat1_label': 'Tamamlanan Proje', 'about_page.stat2_label': 'Ticaret Hacmi',
  'about_page.stat3_label': 'Ülke', 'about_page.stat4_label': 'Müşteri',

  'services_page.badge': 'Ne Yapıyoruz', 'services_page.h1': 'Hizmetlerimiz',
  'services_page.sub': 'Dış ticaret ve uluslararası organizasyonlarda stratejik çözümler sunuyoruz.',
  'services_page.s1.title': 'Uluslararası İş Forumu Organizasyonu',
  'services_page.s1.desc': 'Hedef ülkelerde sektörel iş forumları ve ticaret heyetleri düzenliyoruz; firmaları doğru muhataplarla buluşturuyoruz.',
  'services_page.s2.title': 'Ticaret Heyeti Yönetimi',
  'services_page.s2.desc': 'Resmi ticaret heyetlerinin planlanmasından ulaşım, konaklama ve toplantı ajandalarına tüm süreci yönetiyoruz.',
  'services_page.s3.title': 'Pazar Giriş Danışmanlığı',
  'services_page.s3.desc': 'Yeni pazarlara açılmak isteyen firmalara strateji geliştirmeden doğru iş ortağı bulmaya uçtan uca danışmanlık veriyoruz.',
  'services_page.s4.title': 'Fuar & Expo Katılım',
  'services_page.s4.desc': 'Uluslararası fuar ve expo katılım sürecini baştan sona organize ediyor; sahada profesyonel temsil sağlıyoruz.',
  'services_page.s5.title': 'Kurumsal Ağ Geliştirme',
  'services_page.s5.desc': 'Ticaret odaları ve sanayi birlikleriyle güçlü ilişkilerimiz aracılığıyla doğru kurumsal paydaşlarla buluşturuyoruz.',
  'services_page.s6.title': 'Uluslararası Etkinlik',
  'services_page.s6.desc': 'B2B buluşmaları, ikili iş görüşmeleri ve çok uluslu konferansları profesyonelce planlıyoruz.',

  'faq.badge': 'Yardım Merkezi', 'faq.h1': 'Sıkça Sorulan Sorular',
  'faq.q1': 'Hangi sektörlerde hizmet veriyorsunuz?',
  'faq.a1': 'İhracat, ithalat, lojistik, dış ticaret danışmanlığı ve uluslararası pazarlama alanlarında faaliyet gösteriyoruz.',
  'faq.q2': 'Danışmanlık hizmetiniz şirketimize nasıl fayda sağlar?',
  'faq.a2': 'Süreçlerinizi daha verimli hale getirir, maliyetlerinizi azaltır ve küresel pazarlarda rekabet gücü kazandırırız.',
  'faq.q3': 'Start-up ve KOBİ\'lerle çalışıyor musunuz?',
  'faq.a3': 'Evet, özellikle küçük ve orta ölçekli işletmelere ihracat ve global pazara açılma konularında özel çözümler sunuyoruz.',
  'faq.q4': 'SS Congress hangi ülkelerde hizmet veriyor?',
  'faq.a4': '4 kıta ve 25\'ten fazla ülkede aktif olarak faaliyet gösteriyoruz. Katar, Japonya, Rusya, Hollanda, Suudi Arabistan ve daha pek çok ülkede hizmet sunuyoruz.',
  'faq.q5': 'Bir iş forumu organize ettirmek için süreci nasıl başlatırım?',
  'faq.a5': 'İhtiyacınızı ve hedef pazarınızı birlikte değerlendiriyor, size özel bir organizasyon planı hazırlıyoruz. Tüm süreçler SS Congress tarafından yönetiliyor.',
  'faq.q6': 'SS Congress\'in diğer organizasyon şirketlerinden farkı nedir?',
  'faq.a6': 'Yalnızca etkinlik organize etmiyoruz; aynı zamanda stratejik danışmanlık veriyor, birden fazla ülkenin ticaret bakanlığıyla koordineli çalışıyoruz.',
  'faq.q7': 'Uzun vadeli iş ortaklığı sağlıyor musunuz?',
  'faq.a7': 'Evet, müşterilerimizle uzun soluklu, güvene dayalı iş birlikleri kurmayı hedefliyoruz.',
  'faq.q8': 'Uluslararası mevzuat ve belgeler konusunda yardımcı oluyor musunuz?',
  'faq.a8': 'Evet, gerekli belgeler, sertifikalar ve yasal süreçlerde size rehberlik ediyoruz.',

  'projects_page.badge': 'Portföy', 'projects_page.h1': 'Projelerimiz',
  'projects_page.upcoming': 'Gelecek Projeler', 'projects_page.completed': 'Tamamlanan Projeler',
  'projects_page.active_tag': 'Aktif', 'projects_page.done_tag': 'Tamamlandı',
  'projects_page.cta': 'Detayları İncele',
  'projects_page.kazan': '17. Uluslararası Ekonomi Forumu — Kazan Forum 2026',
  'projects_page.kazan_date': '12-17 Mayıs 2026',

  'career.badge': 'Kariyer', 'career.h1': 'SS Congress Ailesine Katıl',
  'career.sub': 'Küresel ticaretin merkezinde yer alan bir ekibin parçası ol.',
  'career.job_title': 'Ofis Koordinatörü / İdari Asistan',
  'career.location': 'Beştepe / Yenimahalle, Ankara',
  'career.status': 'Açık Pozisyon',
  'career.desc_title': 'İş Tanımı',
  'career.desc': 'Uluslararası dış ticaret organizasyon süreçlerinin koordinasyonu, idari süreçlerin yönetimi ve ekip desteği sağlanması.',
  'career.reqs_title': 'Aranan Özellikler',
  'career.req1': '20-35 yaş aralığında', 'career.req2': 'İyi derecede İngilizce veya Rusça',
  'career.req3': 'Güçlü planlama ve organizasyon', 'career.req4': 'Ekip çalışmasına yatkın',
  'career.req5': 'Ön muhasebe bilgisi (Tercihli)', 'career.req6': 'Esnek çalışmaya yatkın',
  'career.apply': 'Hemen Başvur',
  'career.open_title': 'Genel Başvuru',
  'career.open_desc': 'Mevcut pozisyonlar dışında da özgeçmişinizi paylaşabilirsiniz.',

  'kazan.badge': '17. Uluslararası Ekonomi Forumu', 'kazan.h1': 'Kazan Forum 2026',
  'kazan.details_h2': 'Etkinlik Detayı',
  'kazan.details_p': '17. Uluslararası Ekonomi Forumu Rusya — İslam Dünyası: Kazan Forum 2026, küresel ekonominin en önemli buluşma noktalarından biri olarak İslam dünyası ile Rusya arasındaki stratejik iş birliklerini güçlendirmeyi hedeflemektedir.',
  'kazan.status_h3': 'Mevcut Durum',
  'kazan.status_p': 'Organizasyon ve katılım hazırlıkları SS Congress ekibi tarafından titizlikle sürdürülmektedir. Sektörel delegasyon katılım süreçleri ve ikili iş görüşmeleri (B2B) ajandası planlanmaktadır.',
  'kazan.why_h3': 'Neden Katılmalısınız?',
  'kazan.reason1': 'Stratejik iş ortaklıkları kurma fırsatı',
  'kazan.reason2': 'Küresel pazarda görünürlük artışı',
  'kazan.reason3': 'Üst düzey diplomatik ve ticari ağlara erişim',
  'kazan.reason4': 'Yeni pazarlara giriş danışmanlığı desteği',
  'kazan.date_label': 'Tarih', 'kazan.date_value': '12 - 17 Mayıs 2026',
  'kazan.loc_label': 'Konum', 'kazan.loc_value': 'Kazan, Tataristan / Rusya',
  'kazan.cta': 'Katılım İçin Başvurun', 'kazan.info_title': 'Etkinlik Bilgileri',
};

const en = {
  'nav.home': 'Home', 'nav.about': 'About Us', 'nav.services': 'Services',
  'nav.projects': 'Projects', 'nav.gallery': 'Gallery', 'nav.faq': 'FAQ',
  'nav.career': 'Career', 'nav.contact': 'Contact',
  'lang.tr': 'Türkçe', 'lang.en': 'English', 'lang.ar': 'العربية', 'lang.ru': 'Русский',

  'hero.badge': 'Your Global Business Partner · 25+ Countries',
  'hero.h1_pre': 'Explore the', 'hero.h1_grad': 'World', 'hero.h1_post': 'With Your Partner',
  'hero.sub': 'We provide strategic support to companies entering world markets through international business forums and trade delegations.',
  'hero.cta1': 'Get a Quote', 'hero.cta2': 'Kazan Forum 2026',
  'hero.stat_country': 'Countries', 'hero.stat_client': 'Clients', 'hero.stat_forum': 'Forums', 'hero.stat_year': 'Years',
  'hero.partners': 'Official Partners',

  'about.badge': 'About Us',
  'about.h2_pre': 'Your Trusted Partner', 'about.h2_grad': 'in Global Business',
  'about.p1': 'We simplify the complex structure of international organizations, enabling companies to advance confidently in global markets.',
  'about.p2': 'From Qatar to Japan, from Russia to Africa — we plan and manage business forums and trade delegations end-to-end.',
  'about.point1': 'Ministerial Level Coordination', 'about.point2': 'International Organization Experience',
  'about.point3': 'Global Market Access', 'about.point4': 'Sectoral Forum Expertise',
  'about.globe_hint': 'Click and drag the globe',
  'about.stat_country': 'Countries', 'about.stat_year': 'Years', 'about.stat_forum': 'Forums',

  'services.badge': 'Our Services',
  'services.h2_pre': 'Our Global', 'services.h2_grad': 'Reach Network',
  'services.sub': 'Click a node — view each service\'s content and connected areas',

  'orbital.item1.title': 'International Business Forums', 'orbital.item1.category': 'Service', 'orbital.item1.date': '2019',
  'orbital.item1.content': 'Sectoral business forums and trade delegations in countries such as Qatar, Japan, Russia, and Africa.',
  'orbital.item2.title': 'Ministerial Coordination', 'orbital.item2.category': 'Strategy', 'orbital.item2.date': '2020',
  'orbital.item2.content': 'Direct cooperation with the trade ministries of multiple countries through official channels.',
  'orbital.item3.title': 'Market Entry Consulting', 'orbital.item3.category': 'Consulting', 'orbital.item3.date': '2021',
  'orbital.item3.content': 'End-to-end consulting for companies entering new markets, from strategy to partnerships.',
  'orbital.item4.title': 'Kazan Forum 2026', 'orbital.item4.category': 'Project', 'orbital.item4.date': 'May 2026',
  'orbital.item4.content': '17th International Economic Forum — Russia / Islamic World. Kazan, Tatarstan.',
  'orbital.item5.title': 'Trade Fairs & Expo', 'orbital.item5.category': 'Service', 'orbital.item5.date': '2022',
  'orbital.item5.content': 'Organizing Turkish companies\' participation in global fairs such as Thailand Expo, Russia ProExpo, Berlin ITB.',
  'orbital.item6.title': 'Halal Economy', 'orbital.item6.category': 'Service', 'orbital.item6.date': '2023',
  'orbital.item6.content': 'Specialized solutions on the Makkah Halal Forum and London Halal Forum platforms.',
  'orbital.status.completed': 'Completed', 'orbital.status.inprogress': 'In Progress', 'orbital.status.pending': 'Pending',
  'orbital.capacity': 'Capacity', 'orbital.related': 'Connected Areas',
  'orbital.pause': 'Pause', 'orbital.rotate': 'Rotate',

  'whyus.badge': 'Why SS Congress',
  'whyus.h2_pre': 'Reliable &', 'whyus.h2_grad': 'Effective Trade', 'whyus.h2_post': 'Consulting',
  'whyus.feat1.title': 'Proven Global Experience',
  'whyus.feat1.desc': 'A reference point in the international arena with successful organizations across 4 continents and 25+ countries.',
  'whyus.feat2.title': 'Ministerial Level Coordination',
  'whyus.feat2.desc': 'Direct cooperation with the trade ministries of multiple countries through official channels.',
  'whyus.feat3.title': 'Fast & Effective Solutions',
  'whyus.feat3.desc': 'We elevate your trade to the next level with our process-accelerating strategic approach.',
  'whyus.feat4.title': 'Goal-Oriented Strategy',
  'whyus.feat4.desc': 'Data-driven, results-focused consulting tailored to your growth objectives.',
  'whyus.stat_client': 'Clients', 'whyus.stat_country': 'Countries', 'whyus.stat_forum': 'Forums', 'whyus.stat_year': 'Years',

  'projects.badge': 'Portfolio', 'projects.h2': 'Our Projects',
  'projects.completed': 'Completed Projects', 'projects.upcoming': 'Upcoming Projects',
  'projects.past1': 'Qatar Business Forum 2024', 'projects.past1_loc': 'Doha, Qatar',
  'projects.past2': 'Russia ProExpo Participation', 'projects.past2_loc': 'Moscow, Russia',
  'projects.past3': 'London Halal Forum', 'projects.past3_loc': 'London, UK',
  'projects.past4': 'Makkah Halal Economy Summit', 'projects.past4_loc': 'Makkah, Saudi Arabia',
  'projects.up1': 'Kazan Forum 2026', 'projects.up1_loc': 'Kazan, Tatarstan', 'projects.up1_date': 'May 12–17, 2026',
  'projects.up2': 'Thailand Expo 2025', 'projects.up2_loc': 'Bangkok, Thailand', 'projects.up2_date': '2025',
  'projects.up3': 'Berlin ITB Turkish Delegation', 'projects.up3_loc': 'Berlin, Germany', 'projects.up3_date': '2025',

  'gallery.badge': 'Gallery', 'gallery.h2': 'Behind the Scenes',

  'footer.tagline': 'Your global partner providing strategic, diplomatic, and organizational support to companies entering world markets.',
  'footer.menu': 'Menu', 'footer.corporate': 'Corporate', 'footer.contact_title': 'Contact',
  'footer.faq': 'FAQ', 'footer.career': 'Career',
  'footer.privacy': 'Privacy Policy', 'footer.kvkk': 'Data Protection',
  'footer.copyright': '© SS CONGRESS 2025 — All Rights Reserved',

  'contact.badge': 'Reach Us', 'contact.h1': 'Contact',
  'contact.sub': 'Reach out to us with your questions and consulting requests.',
  'contact.email_title': 'Email', 'contact.phone_title': 'Phone',
  'contact.address_title': 'Address', 'contact.hours_title': 'Working Hours',
  'contact.hours_weekdays': 'Monday - Friday: 09:00 - 18:00',
  'contact.hours_saturday': 'Saturday: 10:00 - 14:00',
  'contact.form_title': 'Get Free Consulting',
  'contact.field_name': 'Full Name', 'contact.field_name_ph': 'Your Full Name',
  'contact.field_email': 'Email', 'contact.field_email_ph': 'email@company.com',
  'contact.field_company': 'Company Name', 'contact.field_company_ph': 'Your company name',
  'contact.field_message': 'Message', 'contact.field_message_ph': 'How can we help you?',
  'contact.submit': 'Send Appointment Request',

  'about_page.badge': 'About Us',
  'about_page.h1_pre': 'Your Trusted Partner', 'about_page.h1_grad': 'in Global Business',
  'about_page.p1': 'We simplify the complex structure of international organizations, enabling companies to advance confidently in global markets.',
  'about_page.p2': 'From Qatar to Japan, from Russia to Africa — we plan and manage business forums and trade delegations end-to-end.',
  'about_page.vision_badge': 'Our Vision',
  'about_page.vision_quote': '"Trust in foreign trade, sustainability at every step."',
  'about_page.process_badge': 'Our Process', 'about_page.process_h2': 'Our Approach',
  'about_page.wf1.title': 'Growth Initiatives',
  'about_page.wf1.desc': 'We support companies on their growth journey with strategic solutions for sustainable success.',
  'about_page.wf2.title': 'Consulting Services',
  'about_page.wf2.desc': 'We guide your business decisions with our expert team and develop future-ready strategies.',
  'about_page.wf3.title': 'Global Initiatives',
  'about_page.wf3.desc': 'We accelerate your business and open it to global markets with data-driven analysis and innovative methods.',
  'about_page.stat1_label': 'Completed Projects', 'about_page.stat2_label': 'Trade Volume',
  'about_page.stat3_label': 'Countries', 'about_page.stat4_label': 'Clients',

  'services_page.badge': 'What We Do', 'services_page.h1': 'Our Services',
  'services_page.sub': 'We provide strategic solutions in foreign trade and international organizations.',
  'services_page.s1.title': 'International Business Forum Organization',
  'services_page.s1.desc': 'We organize sectoral business forums and trade delegations in target countries, connecting companies with the right counterparts.',
  'services_page.s2.title': 'Trade Delegation Management',
  'services_page.s2.desc': 'We manage the entire process from planning official trade delegations to transportation, accommodation, and meeting agendas.',
  'services_page.s3.title': 'Market Entry Consulting',
  'services_page.s3.desc': 'End-to-end consulting for companies entering new markets, from strategy development to finding the right business partner.',
  'services_page.s4.title': 'Trade Fair & Expo Participation',
  'services_page.s4.desc': 'We organize international fair and expo participation start to finish, providing professional on-site representation.',
  'services_page.s5.title': 'Corporate Network Development',
  'services_page.s5.desc': 'Through strong relationships with chambers of commerce and industry associations, we connect companies with the right institutional stakeholders.',
  'services_page.s6.title': 'International Events',
  'services_page.s6.desc': 'We professionally plan B2B meetings, bilateral business talks, and multinational conferences.',

  'faq.badge': 'Help Center', 'faq.h1': 'Frequently Asked Questions',
  'faq.q1': 'Which sectors do you serve?',
  'faq.a1': 'We operate in export, import, logistics, foreign trade consulting, and international marketing.',
  'faq.q2': 'How will your consulting services benefit our company?',
  'faq.a2': 'We make your processes more efficient, reduce costs, and help you gain competitive advantage in global markets.',
  'faq.q3': 'Do you work with start-ups and SMEs?',
  'faq.a3': 'Yes, we provide special solutions especially for small and medium-sized enterprises on export and global market entry.',
  'faq.q4': 'In which countries does SS Congress operate?',
  'faq.a4': 'We actively operate across 4 continents and more than 25 countries, including Qatar, Japan, Russia, the Netherlands, Saudi Arabia, and many more.',
  'faq.q5': 'How do I start the process to organize a business forum?',
  'faq.a5': 'We evaluate your needs and target market together and prepare a custom organization plan. All processes are managed by SS Congress.',
  'faq.q6': 'What distinguishes SS Congress from other event companies?',
  'faq.a6': 'We not only organize events; we also provide strategic consulting and work in coordination with the trade ministries of multiple countries.',
  'faq.q7': 'Do you provide long-term business partnerships?',
  'faq.a7': 'Yes, we aim to establish long-lasting, trust-based collaborations with our clients.',
  'faq.q8': 'Do you assist with international regulations and documentation?',
  'faq.a8': 'Yes, we guide you through the necessary documents, certificates, and legal processes.',

  'projects_page.badge': 'Portfolio', 'projects_page.h1': 'Our Projects',
  'projects_page.upcoming': 'Upcoming Projects', 'projects_page.completed': 'Completed Projects',
  'projects_page.active_tag': 'Active', 'projects_page.done_tag': 'Completed',
  'projects_page.cta': 'View Details',
  'projects_page.kazan': '17th International Economic Forum — Kazan Forum 2026',
  'projects_page.kazan_date': 'May 12-17, 2026',

  'career.badge': 'Career', 'career.h1': 'Join the SS Congress Family',
  'career.sub': 'Be part of a team at the center of global trade.',
  'career.job_title': 'Office Coordinator / Administrative Assistant',
  'career.location': 'Beştepe / Yenimahalle, Ankara',
  'career.status': 'Open Position',
  'career.desc_title': 'Job Description',
  'career.desc': 'Coordinating international foreign trade organization processes, managing administrative processes, and supporting the team.',
  'career.reqs_title': 'Required Qualifications',
  'career.req1': 'Ages 20-35', 'career.req2': 'Good command of English or Russian',
  'career.req3': 'Strong planning and organization skills', 'career.req4': 'Teamwork oriented',
  'career.req5': 'Basic accounting knowledge (Preferred)', 'career.req6': 'Flexible working attitude',
  'career.apply': 'Apply Now',
  'career.open_title': 'Open Application',
  'career.open_desc': 'You can share your CV even outside of current positions.',

  'kazan.badge': '17th International Economic Forum', 'kazan.h1': 'Kazan Forum 2026',
  'kazan.details_h2': 'Event Details',
  'kazan.details_p': 'The 17th International Economic Forum Russia — Islamic World: Kazan Forum 2026 aims to strengthen strategic partnerships between the Islamic world and Russia, as one of the most important meeting points of the global economy.',
  'kazan.status_h3': 'Current Status',
  'kazan.status_p': 'Organization and participation preparations are being carried out meticulously by the SS Congress team. Sectoral delegation participation processes and bilateral business talks (B2B) agenda are being planned.',
  'kazan.why_h3': 'Why Should You Participate?',
  'kazan.reason1': 'Opportunity to establish strategic business partnerships',
  'kazan.reason2': 'Increased visibility in the global market',
  'kazan.reason3': 'Access to high-level diplomatic and commercial networks',
  'kazan.reason4': 'Market entry consulting support',
  'kazan.date_label': 'Date', 'kazan.date_value': 'May 12 - 17, 2026',
  'kazan.loc_label': 'Location', 'kazan.loc_value': 'Kazan, Tatarstan / Russia',
  'kazan.cta': 'Apply to Participate', 'kazan.info_title': 'Event Information',
};

const ar = {
  'nav.home': 'الرئيسية', 'nav.about': 'من نحن', 'nav.services': 'الخدمات',
  'nav.projects': 'المشاريع', 'nav.gallery': 'المعرض', 'nav.faq': 'الأسئلة',
  'nav.career': 'الوظائف', 'nav.contact': 'اتصل بنا',
  'lang.tr': 'Türkçe', 'lang.en': 'English', 'lang.ar': 'العربية', 'lang.ru': 'Русский',

  'hero.badge': 'شريكك التجاري العالمي · 25+ دولة',
  'hero.h1_pre': 'اكتشف', 'hero.h1_grad': 'العالم', 'hero.h1_post': 'مع شريكك التجاري',
  'hero.sub': 'نقدم الدعم الاستراتيجي للشركات الراغبة في دخول الأسواق العالمية من خلال المنتديات التجارية الدولية ووفود الأعمال.',
  'hero.cta1': 'احصل على عرض', 'hero.cta2': 'منتدى قازان 2026',
  'hero.stat_country': 'دولة', 'hero.stat_client': 'عميل', 'hero.stat_forum': 'منتدى', 'hero.stat_year': 'سنة',
  'hero.partners': 'الشركاء الرسميون',

  'about.badge': 'من نحن',
  'about.h2_pre': 'شريكك الموثوق', 'about.h2_grad': 'في عالم الأعمال الدولي',
  'about.p1': 'نبسّط الهيكل المعقد للمنظمات الدولية لنمكّن الشركات من التقدم بثقة في الأسواق العالمية.',
  'about.p2': 'من قطر إلى اليابان، ومن روسيا إلى أفريقيا — نخطط وندير منتديات الأعمال ووفود التجارة من البداية إلى النهاية.',
  'about.point1': 'تنسيق على المستوى الوزاري', 'about.point2': 'خبرة في التنظيم الدولي',
  'about.point3': 'الوصول إلى الأسواق العالمية', 'about.point4': 'خبرة في المنتديات القطاعية',
  'about.globe_hint': 'انقر واسحب الكرة الأرضية',
  'about.stat_country': 'دولة', 'about.stat_year': 'سنة', 'about.stat_forum': 'منتدى',

  'services.badge': 'خدماتنا',
  'services.h2_pre': 'شبكة', 'services.h2_grad': 'وصولنا العالمي',
  'services.sub': 'انقر على عقدة — اعرض محتوى كل خدمة والمجالات المرتبطة بها',

  'orbital.item1.title': 'منتديات الأعمال الدولية', 'orbital.item1.category': 'خدمة', 'orbital.item1.date': '2019',
  'orbital.item1.content': 'منتديات أعمال قطاعية ووفود تجارية في دول كقطر واليابان وروسيا وأفريقيا.',
  'orbital.item2.title': 'التنسيق الوزاري', 'orbital.item2.category': 'استراتيجية', 'orbital.item2.date': '2020',
  'orbital.item2.content': 'تعاون مباشر مع وزارات التجارة في دول متعددة عبر القنوات الرسمية.',
  'orbital.item3.title': 'استشارات دخول السوق', 'orbital.item3.category': 'استشارة', 'orbital.item3.date': '2021',
  'orbital.item3.content': 'استشارات شاملة للشركات الراغبة في دخول أسواق جديدة، من تطوير الاستراتيجية إلى إقامة الشراكات.',
  'orbital.item4.title': 'منتدى قازان 2026', 'orbital.item4.category': 'مشروع', 'orbital.item4.date': 'مايو 2026',
  'orbital.item4.content': 'المنتدى الاقتصادي الدولي السابع عشر — روسيا / العالم الإسلامي. قازان، تتارستان.',
  'orbital.item5.title': 'المعارض التجارية', 'orbital.item5.category': 'خدمة', 'orbital.item5.date': '2022',
  'orbital.item5.content': 'تنظيم مشاركة الشركات التركية في المعارض العالمية كمعرض تايلاند وبرو إكسبو روسيا و ITB برلين.',
  'orbital.item6.title': 'الاقتصاد الحلال', 'orbital.item6.category': 'خدمة', 'orbital.item6.date': '2023',
  'orbital.item6.content': 'حلول متخصصة في منتدى مكة الحلال ومنتدى لندن الحلال.',
  'orbital.status.completed': 'مكتمل', 'orbital.status.inprogress': 'قيد التنفيذ', 'orbital.status.pending': 'قيد الانتظار',
  'orbital.capacity': 'الطاقة', 'orbital.related': 'المجالات المرتبطة',
  'orbital.pause': 'إيقاف', 'orbital.rotate': 'تدوير',

  'whyus.badge': 'لماذا SS Congress',
  'whyus.h2_pre': 'استشارات', 'whyus.h2_grad': 'تجارية موثوقة', 'whyus.h2_post': 'وفعّالة',
  'whyus.feat1.title': 'خبرة عالمية مثبتة',
  'whyus.feat1.desc': 'نعتبر مرجعاً في الساحة الدولية بفضل تنظيمات ناجحة في 4 قارات وأكثر من 25 دولة.',
  'whyus.feat2.title': 'تنسيق على المستوى الوزاري',
  'whyus.feat2.desc': 'نتعاون مباشرة مع وزارات التجارة في دول متعددة عبر القنوات الرسمية.',
  'whyus.feat3.title': 'حلول سريعة وفعّالة',
  'whyus.feat3.desc': 'نرفع تجارتك إلى المستوى التالي بنهجنا الاستراتيجي الذي يُسرّع العمليات.',
  'whyus.feat4.title': 'استراتيجية موجهة نحو الهدف',
  'whyus.feat4.desc': 'نقدم استشارات قائمة على البيانات وتركز على النتائج وفقاً لأهداف نموك.',
  'whyus.stat_client': 'عميل', 'whyus.stat_country': 'دولة', 'whyus.stat_forum': 'منتدى', 'whyus.stat_year': 'سنة',

  'projects.badge': 'المحفظة', 'projects.h2': 'مشاريعنا',
  'projects.completed': 'المشاريع المكتملة', 'projects.upcoming': 'المشاريع القادمة',
  'projects.past1': 'منتدى الأعمال القطري 2024', 'projects.past1_loc': 'الدوحة، قطر',
  'projects.past2': 'المشاركة في ProExpo روسيا', 'projects.past2_loc': 'موسكو، روسيا',
  'projects.past3': 'منتدى لندن الحلال', 'projects.past3_loc': 'لندن، المملكة المتحدة',
  'projects.past4': 'قمة مكة للاقتصاد الحلال', 'projects.past4_loc': 'مكة المكرمة، السعودية',
  'projects.up1': 'منتدى قازان 2026', 'projects.up1_loc': 'قازان، تتارستان', 'projects.up1_date': '12-17 مايو 2026',
  'projects.up2': 'معرض تايلاند 2025', 'projects.up2_loc': 'بانكوك، تايلاند', 'projects.up2_date': '2025',
  'projects.up3': 'وفد ITB برلين التركي', 'projects.up3_loc': 'برلين، ألمانيا', 'projects.up3_date': '2025',

  'gallery.badge': 'المعرض', 'gallery.h2': 'خلف الكواليس',

  'footer.tagline': 'شريكك العالمي الذي يقدم الدعم الاستراتيجي والدبلوماسي والتنظيمي للشركات الراغبة في دخول الأسواق العالمية.',
  'footer.menu': 'القائمة', 'footer.corporate': 'الشركة', 'footer.contact_title': 'تواصل معنا',
  'footer.faq': 'الأسئلة الشائعة', 'footer.career': 'الوظائف',
  'footer.privacy': 'سياسة الخصوصية', 'footer.kvkk': 'حماية البيانات',
  'footer.copyright': '© SS CONGRESS 2025 — جميع الحقوق محفوظة',

  'contact.badge': 'تواصل معنا', 'contact.h1': 'الاتصال',
  'contact.sub': 'تواصل معنا لأسئلتك وطلبات الاستشارة.',
  'contact.email_title': 'البريد الإلكتروني', 'contact.phone_title': 'الهاتف',
  'contact.address_title': 'العنوان', 'contact.hours_title': 'ساعات العمل',
  'contact.hours_weekdays': 'الاثنين - الجمعة: 09:00 - 18:00',
  'contact.hours_saturday': 'السبت: 10:00 - 14:00',
  'contact.form_title': 'احصل على استشارة مجانية',
  'contact.field_name': 'الاسم الكامل', 'contact.field_name_ph': 'اسمك الكامل',
  'contact.field_email': 'البريد الإلكتروني', 'contact.field_email_ph': 'email@company.com',
  'contact.field_company': 'اسم الشركة', 'contact.field_company_ph': 'اسم شركتك',
  'contact.field_message': 'رسالتك', 'contact.field_message_ph': 'كيف يمكننا مساعدتك؟',
  'contact.submit': 'إرسال طلب الموعد',

  'about_page.badge': 'من نحن',
  'about_page.h1_pre': 'شريكك الموثوق', 'about_page.h1_grad': 'في عالم الأعمال الدولي',
  'about_page.p1': 'نبسّط الهيكل المعقد للمنظمات الدولية لنمكّن الشركات من التقدم بثقة في الأسواق العالمية.',
  'about_page.p2': 'من قطر إلى اليابان، ومن روسيا إلى أفريقيا — نخطط وندير منتديات الأعمال ووفود التجارة من البداية إلى النهاية.',
  'about_page.vision_badge': 'رؤيتنا',
  'about_page.vision_quote': '"الثقة في التجارة الخارجية، الاستدامة في كل خطوة."',
  'about_page.process_badge': 'عمليتنا', 'about_page.process_h2': 'نهجنا',
  'about_page.wf1.title': 'مبادرات النمو',
  'about_page.wf1.desc': 'ندعم الشركات في رحلة نموها بحلول استراتيجية لتحقيق نجاح مستدام.',
  'about_page.wf2.title': 'خدمات الاستشارة',
  'about_page.wf2.desc': 'نرشد قراراتك التجارية بفريقنا من الخبراء ونطور استراتيجيات مستقبلية.',
  'about_page.wf3.title': 'المبادرات العالمية',
  'about_page.wf3.desc': 'نسرّع أعمالك ونفتحها على الأسواق العالمية بالتحليل القائم على البيانات والأساليب المبتكرة.',
  'about_page.stat1_label': 'مشروع مكتمل', 'about_page.stat2_label': 'حجم التجارة',
  'about_page.stat3_label': 'دولة', 'about_page.stat4_label': 'عميل',

  'services_page.badge': 'ما نقدمه', 'services_page.h1': 'خدماتنا',
  'services_page.sub': 'نقدم حلولاً استراتيجية في التجارة الخارجية والمنظمات الدولية.',
  'services_page.s1.title': 'تنظيم منتديات الأعمال الدولية',
  'services_page.s1.desc': 'نُنظّم منتديات الأعمال القطاعية ووفود التجارة في الدول المستهدفة، ونربط الشركات بالشركاء المناسبين.',
  'services_page.s2.title': 'إدارة وفود التجارة',
  'services_page.s2.desc': 'ندير العملية بأكملها من تخطيط الوفود التجارية الرسمية إلى النقل والإقامة وجداول الاجتماعات.',
  'services_page.s3.title': 'استشارات دخول السوق',
  'services_page.s3.desc': 'نقدم استشارات شاملة للشركات الراغبة في دخول أسواق جديدة، من تطوير الاستراتيجية إلى إيجاد الشريك المناسب.',
  'services_page.s4.title': 'المشاركة في المعارض',
  'services_page.s4.desc': 'ننظم المشاركة في المعارض الدولية من البداية للنهاية، ونوفر تمثيلاً احترافياً في الميدان.',
  'services_page.s5.title': 'تطوير الشبكة المؤسسية',
  'services_page.s5.desc': 'من خلال علاقاتنا القوية مع غرف التجارة والاتحادات الصناعية، نربط الشركات بأصحاب المصلحة المؤسسيين المناسبين.',
  'services_page.s6.title': 'الفعاليات الدولية',
  'services_page.s6.desc': 'نخطط باحترافية لاجتماعات B2B والمحادثات التجارية الثنائية والمؤتمرات متعددة الجنسيات.',

  'faq.badge': 'مركز المساعدة', 'faq.h1': 'الأسئلة المتداولة',
  'faq.q1': 'ما القطاعات التي تخدمونها؟',
  'faq.a1': 'نعمل في مجالات التصدير والاستيراد والخدمات اللوجستية والاستشارات التجارية الخارجية والتسويق الدولي.',
  'faq.q2': 'كيف ستفيد خدماتك الاستشارية شركتنا؟',
  'faq.a2': 'نجعل عملياتك أكثر كفاءة ونقلل التكاليف ونساعدك على اكتساب ميزة تنافسية في الأسواق العالمية.',
  'faq.q3': 'هل تعملون مع الشركات الناشئة والمشاريع الصغيرة والمتوسطة؟',
  'faq.a3': 'نعم، نقدم حلولاً خاصة للشركات الصغيرة والمتوسطة في مجال التصدير ودخول الأسواق العالمية.',
  'faq.q4': 'في أي دول يعمل SS Congress؟',
  'faq.a4': 'نعمل بنشاط في 4 قارات وأكثر من 25 دولة، بما فيها قطر واليابان وروسيا وهولندا والسعودية وغيرها.',
  'faq.q5': 'كيف أبدأ عملية تنظيم منتدى أعمال؟',
  'faq.a5': 'نقيّم معك احتياجاتك وسوقك المستهدف ونضع خطة تنظيمية مخصصة. تُدار جميع العمليات من قبل SS Congress.',
  'faq.q6': 'ما الذي يميز SS Congress عن شركات الفعاليات الأخرى؟',
  'faq.a6': 'لا نكتفي بتنظيم الفعاليات؛ بل نقدم أيضاً استشارات استراتيجية ونعمل بالتنسيق مع وزارات التجارة في دول متعددة.',
  'faq.q7': 'هل تقدمون شراكات تجارية طويلة الأمد؟',
  'faq.a7': 'نعم، نهدف إلى إقامة تعاونات قائمة على الثقة وطويلة الأمد مع عملائنا.',
  'faq.q8': 'هل تساعدون في اللوائح والوثائق الدولية؟',
  'faq.a8': 'نعم، نرشدك في الوثائق والشهادات والإجراءات القانونية اللازمة.',

  'projects_page.badge': 'المحفظة', 'projects_page.h1': 'مشاريعنا',
  'projects_page.upcoming': 'المشاريع القادمة', 'projects_page.completed': 'المشاريع المكتملة',
  'projects_page.active_tag': 'نشط', 'projects_page.done_tag': 'مكتمل',
  'projects_page.cta': 'عرض التفاصيل',
  'projects_page.kazan': 'المنتدى الاقتصادي الدولي السابع عشر — منتدى قازان 2026',
  'projects_page.kazan_date': '12-17 مايو 2026',

  'career.badge': 'الوظائف', 'career.h1': 'انضم إلى عائلة SS Congress',
  'career.sub': 'كن جزءاً من فريق في قلب التجارة العالمية.',
  'career.job_title': 'منسق المكتب / مساعد إداري',
  'career.location': 'بيشتيبه / ينيماهاله، أنقرة',
  'career.status': 'وظيفة شاغرة',
  'career.desc_title': 'وصف الوظيفة',
  'career.desc': 'تنسيق عمليات تنظيم التجارة الخارجية الدولية وإدارة العمليات الإدارية وتقديم الدعم للفريق.',
  'career.reqs_title': 'المؤهلات المطلوبة',
  'career.req1': 'من عمر 20 إلى 35 سنة', 'career.req2': 'إجادة جيدة للإنجليزية أو الروسية',
  'career.req3': 'مهارات قوية في التخطيط والتنظيم', 'career.req4': 'موجه نحو العمل الجماعي',
  'career.req5': 'معرفة المحاسبة الأساسية (مفضّل)', 'career.req6': 'استعداد للعمل المرن',
  'career.apply': 'قدّم الآن',
  'career.open_title': 'طلب مفتوح',
  'career.open_desc': 'يمكنك مشاركة سيرتك الذاتية حتى خارج الوظائف الشاغرة الحالية.',

  'kazan.badge': 'المنتدى الاقتصادي الدولي السابع عشر', 'kazan.h1': 'منتدى قازان 2026',
  'kazan.details_h2': 'تفاصيل الفعالية',
  'kazan.details_p': 'المنتدى الاقتصادي الدولي السابع عشر روسيا — العالم الإسلامي: منتدى قازان 2026 يهدف إلى تعزيز الشراكات الاستراتيجية بين العالم الإسلامي وروسيا، بوصفه أحد أبرز نقاط اللقاء في الاقتصاد العالمي.',
  'kazan.status_h3': 'الوضع الراهن',
  'kazan.status_p': 'يجري فريق SS Congress بدقة إعداد التنظيم وترتيبات المشاركة. يُخطط حالياً لعمليات مشاركة الوفود القطاعية وجدول الاجتماعات التجارية الثنائية B2B.',
  'kazan.why_h3': 'لماذا يجب المشاركة؟',
  'kazan.reason1': 'فرصة لإنشاء شراكات تجارية استراتيجية',
  'kazan.reason2': 'زيادة الظهور في السوق العالمية',
  'kazan.reason3': 'الوصول إلى الشبكات الدبلوماسية والتجارية رفيعة المستوى',
  'kazan.reason4': 'دعم استشارات دخول الأسواق الجديدة',
  'kazan.date_label': 'التاريخ', 'kazan.date_value': '12 - 17 مايو 2026',
  'kazan.loc_label': 'الموقع', 'kazan.loc_value': 'قازان، تتارستان / روسيا',
  'kazan.cta': 'تقدم للمشاركة', 'kazan.info_title': 'معلومات الفعالية',
};

const ru = {
  'nav.home': 'Главная', 'nav.about': 'О нас', 'nav.services': 'Услуги',
  'nav.projects': 'Проекты', 'nav.gallery': 'Галерея', 'nav.faq': 'Вопросы',
  'nav.career': 'Карьера', 'nav.contact': 'Контакты',
  'lang.tr': 'Türkçe', 'lang.en': 'English', 'lang.ar': 'العربية', 'lang.ru': 'Русский',

  'hero.badge': 'Ваш глобальный деловой партнёр · 25+ стран',
  'hero.h1_pre': 'Откройте', 'hero.h1_grad': 'Мир', 'hero.h1_post': 'Со Своим Партнёром',
  'hero.sub': 'Мы оказываем стратегическую поддержку компаниям, выходящим на мировые рынки, через международные бизнес-форумы и торговые делегации.',
  'hero.cta1': 'Получить предложение', 'hero.cta2': 'Казань Форум 2026',
  'hero.stat_country': 'Стран', 'hero.stat_client': 'Клиентов', 'hero.stat_forum': 'Форумов', 'hero.stat_year': 'Лет',
  'hero.partners': 'Официальные партнёры',

  'about.badge': 'О нас',
  'about.h2_pre': 'Ваш надёжный партнёр', 'about.h2_grad': 'в глобальном бизнесе',
  'about.p1': 'Мы упрощаем сложную структуру международных организаций, позволяя компаниям уверенно продвигаться на мировых рынках.',
  'about.p2': 'От Катара до Японии, от России до Африки — мы планируем и управляем бизнес-форумами и торговыми делегациями от начала до конца.',
  'about.point1': 'Координация на уровне министерств', 'about.point2': 'Опыт международных организаций',
  'about.point3': 'Доступ к мировым рынкам', 'about.point4': 'Экспертиза отраслевых форумов',
  'about.globe_hint': 'Нажмите и перетащите глобус',
  'about.stat_country': 'Стран', 'about.stat_year': 'Лет', 'about.stat_forum': 'Форумов',

  'services.badge': 'Наши услуги',
  'services.h2_pre': 'Наша глобальная', 'services.h2_grad': 'сеть охвата',
  'services.sub': 'Нажмите на узел — посмотрите содержание каждой услуги и связанные области',

  'orbital.item1.title': 'Международные бизнес-форумы', 'orbital.item1.category': 'Услуга', 'orbital.item1.date': '2019',
  'orbital.item1.content': 'Отраслевые бизнес-форумы и торговые делегации в Катаре, Японии, России и Африке.',
  'orbital.item2.title': 'Министерская координация', 'orbital.item2.category': 'Стратегия', 'orbital.item2.date': '2020',
  'orbital.item2.content': 'Прямое сотрудничество с министерствами торговли нескольких стран через официальные каналы.',
  'orbital.item3.title': 'Консалтинг выхода на рынок', 'orbital.item3.category': 'Консалтинг', 'orbital.item3.date': '2021',
  'orbital.item3.content': 'Комплексный консалтинг для компаний, выходящих на новые рынки: от стратегии до партнёрства.',
  'orbital.item4.title': 'Казань Форум 2026', 'orbital.item4.category': 'Проект', 'orbital.item4.date': 'Май 2026',
  'orbital.item4.content': '17-й Международный экономический форум — Россия / Исламский мир. Казань, Татарстан.',
  'orbital.item5.title': 'Выставки и экспо', 'orbital.item5.category': 'Услуга', 'orbital.item5.date': '2022',
  'orbital.item5.content': 'Организация участия турецких компаний в Thailand Expo, РосПроЭкспо, ITB Берлин.',
  'orbital.item6.title': 'Халяльная экономика', 'orbital.item6.category': 'Услуга', 'orbital.item6.date': '2023',
  'orbital.item6.content': 'Специализированные решения на платформах Мекканского и Лондонского халяльных форумов.',
  'orbital.status.completed': 'Завершено', 'orbital.status.inprogress': 'В процессе', 'orbital.status.pending': 'Ожидается',
  'orbital.capacity': 'Ёмкость', 'orbital.related': 'Связанные области',
  'orbital.pause': 'Стоп', 'orbital.rotate': 'Вращать',

  'whyus.badge': 'Почему SS Congress',
  'whyus.h2_pre': 'Надёжный и', 'whyus.h2_grad': 'эффективный', 'whyus.h2_post': 'консалтинг',
  'whyus.feat1.title': 'Подтверждённый глобальный опыт',
  'whyus.feat1.desc': 'Мы — референтная точка на международной арене с организациями на 4 континентах и в 25+ странах.',
  'whyus.feat2.title': 'Координация на уровне министерств',
  'whyus.feat2.desc': 'Мы напрямую сотрудничаем с министерствами торговли нескольких стран через официальные каналы.',
  'whyus.feat3.title': 'Быстрые и эффективные решения',
  'whyus.feat3.desc': 'Мы выводим вашу торговлю на следующий уровень стратегическим подходом, ускоряющим процессы.',
  'whyus.feat4.title': 'Целеориентированная стратегия',
  'whyus.feat4.desc': 'Консалтинг на основе данных и ориентированный на результат, соответствующий вашим целям роста.',
  'whyus.stat_client': 'Клиентов', 'whyus.stat_country': 'Стран', 'whyus.stat_forum': 'Форумов', 'whyus.stat_year': 'Лет',

  'projects.badge': 'Портфель', 'projects.h2': 'Наши проекты',
  'projects.completed': 'Завершённые проекты', 'projects.upcoming': 'Предстоящие проекты',
  'projects.past1': 'Катарский бизнес-форум 2024', 'projects.past1_loc': 'Доха, Катар',
  'projects.past2': 'Участие в РосПроЭкспо', 'projects.past2_loc': 'Москва, Россия',
  'projects.past3': 'Лондонский халяльный форум', 'projects.past3_loc': 'Лондон, Великобритания',
  'projects.past4': 'Мекканский саммит халяльной экономики', 'projects.past4_loc': 'Мекка, Саудовская Аравия',
  'projects.up1': 'Казань Форум 2026', 'projects.up1_loc': 'Казань, Татарстан', 'projects.up1_date': '12–17 мая 2026',
  'projects.up2': 'Thailand Expo 2025', 'projects.up2_loc': 'Бангкок, Таиланд', 'projects.up2_date': '2025',
  'projects.up3': 'Турецкая делегация на ITB Берлин', 'projects.up3_loc': 'Берлин, Германия', 'projects.up3_date': '2025',

  'gallery.badge': 'Галерея', 'gallery.h2': 'За кулисами',

  'footer.tagline': 'Ваш глобальный партнёр, оказывающий стратегическую, дипломатическую и организационную поддержку компаниям, выходящим на мировые рынки.',
  'footer.menu': 'Меню', 'footer.corporate': 'Компания', 'footer.contact_title': 'Контакты',
  'footer.faq': 'Вопросы', 'footer.career': 'Карьера',
  'footer.privacy': 'Политика конфиденциальности', 'footer.kvkk': 'Защита данных',
  'footer.copyright': '© SS CONGRESS 2025 — Все права защищены',

  'contact.badge': 'Свяжитесь с нами', 'contact.h1': 'Контакты',
  'contact.sub': 'Свяжитесь с нами по вашим вопросам и запросам на консультацию.',
  'contact.email_title': 'Эл. почта', 'contact.phone_title': 'Телефон',
  'contact.address_title': 'Адрес', 'contact.hours_title': 'Рабочие часы',
  'contact.hours_weekdays': 'Пн - Пт: 09:00 - 18:00',
  'contact.hours_saturday': 'Сб: 10:00 - 14:00',
  'contact.form_title': 'Получить бесплатную консультацию',
  'contact.field_name': 'Полное имя', 'contact.field_name_ph': 'Ваше полное имя',
  'contact.field_email': 'Эл. почта', 'contact.field_email_ph': 'email@company.com',
  'contact.field_company': 'Название компании', 'contact.field_company_ph': 'Название вашей компании',
  'contact.field_message': 'Сообщение', 'contact.field_message_ph': 'Чем мы можем вам помочь?',
  'contact.submit': 'Отправить запрос на встречу',

  'about_page.badge': 'О нас',
  'about_page.h1_pre': 'Ваш надёжный партнёр', 'about_page.h1_grad': 'в глобальном бизнесе',
  'about_page.p1': 'Мы упрощаем сложную структуру международных организаций, позволяя компаниям уверенно продвигаться на мировых рынках.',
  'about_page.p2': 'От Катара до Японии, от России до Африки — мы планируем и управляем бизнес-форумами и торговыми делегациями от начала до конца.',
  'about_page.vision_badge': 'Наше видение',
  'about_page.vision_quote': '"Доверие во внешней торговле, устойчивость на каждом шагу."',
  'about_page.process_badge': 'Наш процесс', 'about_page.process_h2': 'Наш подход',
  'about_page.wf1.title': 'Инициативы роста',
  'about_page.wf1.desc': 'Мы поддерживаем компании на пути к росту стратегическими решениями для устойчивого успеха.',
  'about_page.wf2.title': 'Консалтинговые услуги',
  'about_page.wf2.desc': 'Мы направляем ваши бизнес-решения с командой экспертов и разрабатываем стратегии будущего.',
  'about_page.wf3.title': 'Глобальные инициативы',
  'about_page.wf3.desc': 'Мы ускоряем ваш бизнес и открываем его мировым рынкам с помощью аналитики и инноваций.',
  'about_page.stat1_label': 'Завершённых проектов', 'about_page.stat2_label': 'Объём торговли',
  'about_page.stat3_label': 'Стран', 'about_page.stat4_label': 'Клиентов',

  'services_page.badge': 'Что мы делаем', 'services_page.h1': 'Наши услуги',
  'services_page.sub': 'Мы предоставляем стратегические решения во внешней торговле и международных организациях.',
  'services_page.s1.title': 'Организация международных бизнес-форумов',
  'services_page.s1.desc': 'Мы организуем отраслевые бизнес-форумы и торговые делегации в целевых странах, соединяя компании с нужными партнёрами.',
  'services_page.s2.title': 'Управление торговыми делегациями',
  'services_page.s2.desc': 'Управляем всем процессом от планирования официальных торговых делегаций до транспорта, проживания и повестки встреч.',
  'services_page.s3.title': 'Консалтинг выхода на рынок',
  'services_page.s3.desc': 'Комплексный консалтинг от разработки стратегии до поиска нужного бизнес-партнёра.',
  'services_page.s4.title': 'Участие в выставках и экспо',
  'services_page.s4.desc': 'Организуем международное участие в выставках от начала до конца с профессиональным представлением на месте.',
  'services_page.s5.title': 'Развитие корпоративной сети',
  'services_page.s5.desc': 'Через прочные связи с торгово-промышленными палатами и отраслевыми ассоциациями соединяем компании с нужными партнёрами.',
  'services_page.s6.title': 'Международные мероприятия',
  'services_page.s6.desc': 'Профессионально планируем встречи B2B, двусторонние переговоры и многонациональные конференции.',

  'faq.badge': 'Центр помощи', 'faq.h1': 'Часто задаваемые вопросы',
  'faq.q1': 'В каких секторах вы работаете?',
  'faq.a1': 'Мы работаем в области экспорта, импорта, логистики, консалтинга во внешней торговле и международного маркетинга.',
  'faq.q2': 'Как ваши консалтинговые услуги принесут пользу нашей компании?',
  'faq.a2': 'Мы сделаем ваши процессы эффективнее, снизим затраты и поможем получить конкурентное преимущество на мировых рынках.',
  'faq.q3': 'Работаете ли вы со стартапами и МСП?',
  'faq.a3': 'Да, мы предоставляем специальные решения для малых и средних предприятий по экспорту и выходу на мировой рынок.',
  'faq.q4': 'В каких странах работает SS Congress?',
  'faq.a4': 'Мы активно работаем на 4 континентах и в более чем 25 странах: Катар, Япония, Россия, Нидерланды, Саудовская Аравия и многие другие.',
  'faq.q5': 'Как начать процесс организации бизнес-форума?',
  'faq.a5': 'Мы вместе оцениваем ваши потребности и целевой рынок и готовим индивидуальный план. Все процессы управляются SS Congress.',
  'faq.q6': 'Чем SS Congress отличается от других event-компаний?',
  'faq.a6': 'Мы не только организуем мероприятия, но и предоставляем стратегический консалтинг, координируясь с министерствами торговли разных стран.',
  'faq.q7': 'Обеспечиваете ли вы долгосрочное деловое партнёрство?',
  'faq.a7': 'Да, мы стремимся к долгосрочному сотрудничеству на основе доверия с нашими клиентами.',
  'faq.q8': 'Помогаете ли вы с международными нормативами и документацией?',
  'faq.a8': 'Да, мы сопровождаем вас при работе с документами, сертификатами и юридическими процессами.',

  'projects_page.badge': 'Портфель', 'projects_page.h1': 'Наши проекты',
  'projects_page.upcoming': 'Предстоящие проекты', 'projects_page.completed': 'Завершённые проекты',
  'projects_page.active_tag': 'Активный', 'projects_page.done_tag': 'Завершён',
  'projects_page.cta': 'Подробнее',
  'projects_page.kazan': '17-й Международный экономический форум — Казань Форум 2026',
  'projects_page.kazan_date': '12-17 мая 2026',

  'career.badge': 'Карьера', 'career.h1': 'Присоединяйтесь к семье SS Congress',
  'career.sub': 'Станьте частью команды в центре глобальной торговли.',
  'career.job_title': 'Координатор офиса / Административный ассистент',
  'career.location': 'Бештепе / Йенимахалле, Анкара',
  'career.status': 'Открытая вакансия',
  'career.desc_title': 'Описание должности',
  'career.desc': 'Координация международных процессов организации внешней торговли, управление административными процессами и поддержка команды.',
  'career.reqs_title': 'Требуемые квалификации',
  'career.req1': 'Возраст 20-35 лет', 'career.req2': 'Хорошее знание английского или русского',
  'career.req3': 'Сильные навыки планирования и организации', 'career.req4': 'Ориентированность на командную работу',
  'career.req5': 'Базовые знания бухгалтерского учёта (желательно)', 'career.req6': 'Готовность к гибкому графику',
  'career.apply': 'Подать заявку',
  'career.open_title': 'Открытая заявка',
  'career.open_desc': 'Вы можете поделиться резюме даже вне текущих вакансий.',

  'kazan.badge': '17-й Международный экономический форум', 'kazan.h1': 'Казань Форум 2026',
  'kazan.details_h2': 'Детали мероприятия',
  'kazan.details_p': '17-й Международный экономический форум Россия — Исламский мир: Казань Форум 2026 направлен на укрепление стратегических партнёрств между исламским миром и Россией.',
  'kazan.status_h3': 'Текущий статус',
  'kazan.status_p': 'Организация и подготовка к участию ведутся командой SS Congress. Планируются процессы участия отраслевых делегаций и повестка двусторонних деловых переговоров B2B.',
  'kazan.why_h3': 'Почему стоит участвовать?',
  'kazan.reason1': 'Возможность установить стратегические деловые партнёрства',
  'kazan.reason2': 'Повышение видимости на мировом рынке',
  'kazan.reason3': 'Доступ к высокоуровневым дипломатическим и торговым сетям',
  'kazan.reason4': 'Поддержка консалтинга по выходу на новые рынки',
  'kazan.date_label': 'Дата', 'kazan.date_value': '12 - 17 мая 2026',
  'kazan.loc_label': 'Место', 'kazan.loc_value': 'Казань, Татарстан / Россия',
  'kazan.cta': 'Подать заявку на участие', 'kazan.info_title': 'Информация о мероприятии',
};

const translations = { tr, en, ar, ru };

export const LANGUAGES = [
  { code: 'tr', label: 'Türkçe' },
  { code: 'en', label: 'English' },
  { code: 'ar', label: 'العربية' },
  { code: 'ru', label: 'Русский' },
];

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    try { return localStorage.getItem('ss-lang') || 'tr'; } catch { return 'tr'; }
  });

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    try { localStorage.setItem('ss-lang', language); } catch {}
  }, [language]);

  const t = useCallback((key) => {
    return translations[language]?.[key] ?? translations.tr[key] ?? key;
  }, [language]);

  const dir = language === 'ar' ? 'rtl' : 'ltr';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
